name: Deploy Blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init --recursive

      - id: git-sha-short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.13

      - name: build
        run: earthly --ci +build

      - name: Log in to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        run: earthly --ci --push +docker --VERSION ${{ steps.git-sha-short.outputs.sha_short }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - id: git-sha-short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - run: sed -i 's/CHANGE_ME/'${{ steps.git-sha-short.outputs.sha_short }}'/' deploy.yml

      - run: cat deploy.yml

      - uses: ./actions/akash
        with:
          AKASH_WALLET_KEY: ${{ secrets.AKASH_WALLET_KEY }}
          AKASH_WALLET_KEY_PASSWORD: ${{ secrets.AKASH_WALLET_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AKASH_DEPLOY_CERTIFICATE: ${{ secrets.AKASH_DEPLOY_CERTIFICATE }}
          AKASH_DSEQ: 5355872
          AKASH_PROVIDER: akash1fjsgc7uy2vy23juehaja3f5wzfqu8wd6rwck7p